#!/bin/sh

mkdir opk/
git pull
cp icons/gpsp.png opk/
cp COPYING.DOC opk/
cp gpsp.sh opk/
cp gba_launch_gpsp.sh opk/
cp instant_play opk/
cd chip/
make clean
make
/opt/FunKey-sdk/bin/arm-funkey-linux-musleabihf-strip gpsp
cd -
cp chip/gpsp opk/

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GMenu2X entry file plus other things

print '[Desktop Entry]
Name=gpSP
Comment=Game Boy Advance emulator
Exec=gpsp.sh %f
Icon=gpsp
Categories=emulators
SelectorFilter=gba,zip' > opk/gpsp.funkey-s.desktop

mksquashfs opk/ gpsp_v1.2.3_funkey-s.opk -all-root -noappend -no-exports -no-xattrs

rm -rf opk/
